### ISSUE TITLE
clang error - Possible path problem?

### ISSUE THREAD

**Issue by Josh-Miller** [pegli/couchbase_ti#12]
Okay so I have not been able to get this module to work so far. I think it has something to do with file paths. My titanium directory is installed in my Macintosh HD folder the very root of my mac, not in the user. I have the Couchbase frameworks placed in both the mac root frameworks folder as well as my user frameworks folder. I have placed the actual module in the root of my project folder as well as the root of my mac titanium modules folder. So far i have not been able to get the app to run when i have paced the module in my tiapp.xml. The current error I get is:

[ERROR] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR] 
[ERROR] Error: Traceback (most recent call last):
  File "/Library/Application Support/Titanium/mobilesdk/osx/1.8.0.1/iphone/builder.py", line 1274, in main
    execute_xcode("iphonesimulator%s" % link_version,["GCC_PREPROCESSOR_DEFINITIONS=**LOG__ID**=%s DEPLOYTYPE=development TI_DEVELOPMENT=1 DEBUG=1 TI_VERSION=%s %s %s" % (log_id,sdk_version,debugstr,kroll_coverage)],False)
  File "/Library/Application Support/Titanium/mobilesdk/osx/1.8.0.1/iphone/builder.py", line 1180, in execute_xcode
    output = run.run(args,False,False,o)
  File "/Library/Application Support/Titanium/mobilesdk/osx/1.8.0.1/iphone/run.py", line 39, in run
    sys.exit(rc)
SystemExit: 65

This is all done on a clean build. Does anyone have any ideas?

**Comment by pegli** [comment]
When you get a "SystemExit: 65" error, it usually means that the `xcodebuild` step in the Python build script failed.  There should be a build log file that tells you what happened.  My guess, though, is that the linker couldn't find either the Couchbase framework or the Titanium SDK.  Take a look at `module.xcconfig` and `titanium.xcconfig` to make sure all of the paths are correct for your setup.

**Comment by Josh-Miller** [comment]
Ah I finally solved the problem. I think I had an older download of couchbase. The other problem was mac had locked the file permissions. Once I fixed those things it worked for me! Thanks so much ;)
