### ISSUE TITLE
Error "Couldn't find module..."

### ISSUE THREAD

**Issue by ghost** [pegli/couchbase_ti#4]
First of all, thanks for your work here.

I am having trouble getting this working in my titanium project. I followed your instructions and did a build for iOS from scratch. I copied the generated ZIP file into /Library/Application Support/Titanium/mobilesdk/1.7.1 - which is the version I am building with.

I changed tiapp.xml:

``` xml
<module platform="iphone" version="1.0">com.obscure.couchbase_ti</module>
```

I added the following code to my app.js:

``` javascript
var couchbase = require('com.obscure.couchbase_ti');
var serverUrl;
server.addEventListener("com.obscure.couchbase_ti.server_started", function(e) {
  serverUrl = e.serverUrl;
});
server.startCouchbase();
```

In the Console I can see the following relevent lines:

``` text
[DEBUG] Detecting modules in /Users/Matthew/Titanium/XXX/modules
[DEBUG] Detecting modules in /Library/Application Support/Titanium/modules
[DEBUG] Looking for Titanium Module id: com.obscure.couchbase_ti, version: 1.0, platform: iphone
[INFO] Skipping JS compile, running from simulator
Syntax error at 'LexToken(:,':',1,418)'
Syntax error at 'LexToken(/,'/',1,447)'
Syntax error at 'LexToken(;,';',1,477)'
[INFO] Performing clean build
...
[DEBUG] Xcode 4.0.2
[DEBUG] Build version 4A2002a
[INFO] Found 4.3.2 patch installed
[INFO] Application started
...

[INFO] starting couchdb (my own logging output)

[DEBUG] loading: /Users/Matthew/Titanium/XXX/Resources/com.obscure.couchbase_ti.js, resource: Users/Matthew/Titanium/XXX/Resources/com_obscure_couchbase_ti_js

[ERROR] Script Error = Couldn't find module: com.obscure.couchbase_ti.

[DEBUG] application booted in 37.642002 ms
```

What is this "Resources/com.obscure.couchbase_ti.js" that it mentions here? 

Is there anything I am obviously doing wrong?

FYI - I also unzipped the ZIP file and can see the folders as expected. I also performed clean builds.

Thanks for your help.

Matthew

**Comment by ghost** [comment]
No clues ?

**Comment by pegli** [comment]
Hi Matthew -

I'm not sure if you're still interested in this project, but I've updated the module to work with the new release of Couchbase Mobile for iOS, and you might have better luck with it now.  Check out the [installation instructions](https://github.com/pegli/couchbase_ti/wiki/Using-couchbase_ti) on the wiki for details on how to get the module working with your app.

I haven't been able to reproduce your problem with the latest code, so I'm closing the bug.  If you still run into issues, feel free to reopen this bug or contact me via email.

--paul
