### ISSUE TITLE
CouchbaseResources path

### ISSUE THREAD

**Issue by thiagobc** [pegli/couchbase_ti#5]
I'm using XCode 3.2.6, so I'm not sure if this is an issue or not.

I had an error when trying to load the default_ios.ini from CouchbaseResources directory.
So I noticed that the "[[NSBundle mainBundle] bundlePath]" returned the application root directory, and not the "modules" one.
In order to fix it,  I changed the following line into ComObscureCouchbase_tiModule.m from:

``` objectivec
NSString * resourcesPath = [[NSBundle mainBundle] pathForResource:@"CouchbaseResources" ofType:nil inDirectory:@"com.obscure.couchbase_ti/1.0/assets"];
```

to:

``` objectivec
NSString * resourcesPath = [[NSBundle mainBundle] pathForResource:@"CouchbaseResources" ofType:nil inDirectory:@"modules/com.obscure.couchbase_ti/1.0/assets"];
```

Thanks

**Comment by pegli** [comment]
The resources path has changed again for Titanium 1.7.3 and Couchbase Mobile for iOS 2.0 beta.  I've updated the module with the proper resources path -- please try version 1.0.1 and let me know if you still have any issues.  Thanks!

--paul
