### ISSUE TITLE
Terminating in do_boot

### ISSUE THREAD

**Issue by mediahack** [pegli/couchbase_ti#9]
[INFO] My App/1.0 (1.8.0.1.fbdc96f)
{"init terminating in do_boot",{'cannot get bootfile','/Users/dev/Library/Application Support/iPhone Simulator/5.0/Applications/AAE9A47A-CE6F-485D-9BAE-597A4DF16DB6/My App.app/modules/com.obscure.couchbase_ti/CouchbaseResources/erlang/bin/start.boot'}}
[INFO] Application has exited from Simulator

**Comment by pegli** [comment]
Version 1.0.2 of the module was not compatible with the CouchbaseMobile 2.0.0 release.  I've rebuilt the module using that version of CouchbaseMobile and have successfully built the CouchBooks sample app.  Please download the latest version from https://github.com/pegli/couchbase_ti/downloads and rebuilt your app.  Make sure you delete the build folder before rebuilding!

**Comment by mediahack** [comment]
Works!
